from .gstt import (
    DAY1_ARRIVAL,
    WGS_WORKSHEET,
    STOCK_RETRIEVAL,
    UNCAP_TUBES,
    TRANSFER_DNA,
    RECAP_TUBES,
    NUCLEIC_ACID_QC,
    QUANTIFICATION_READING,
    CREATE_DILUTION_TUBES,
    CREATE_PLATE_FOR_TRANSFER_TO_HUB,
    STOCK_DNA_FREEZER,
    RACK_OF_BARCODED_TUBES,
)

GSTT_PROCESS_STEPS = [
    DAY1_ARRIVAL,
    WGS_WORKSHEET,
    STOCK_RETRIEVAL,
    UNCAP_TUBES,
    TRANSFER_DNA,
    RECAP_TUBES,
    NUCLEIC_ACID_QC,
    QUANTIFICATION_READING,
    CREATE_DILUTION_TUBES,
    CREATE_PLATE_FOR_TRANSFER_TO_HUB,
    RACK_OF_BARCODED_TUBES,
]

__all__ = [
    "DAY1_ARRIVAL",
    "WGS_WORKSHEET",
    "STOCK_RETRIEVAL",
    "UNCAP_TUBES",
    "TRANSFER_DNA",
    "RECAP_TUBES",
    "NUCLEIC_ACID_QC",
    "QUANTIFICATION_READING",
    "CREATE_DILUTION_TUBES",
    "CREATE_PLATE_FOR_TRANSFER_TO_HUB",
    "STOCK_DNA_FREEZER",
    "RACK_OF_BARCODED_TUBES",
]